/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fantasy0v0.dinoFx;

import fantasy0v0.dinoFx.obj.Game;
import fantasy0v0.dinoFx.resources.Resources;
import fantasy0v0.dinoFx.utils.Time;
import javafx.animation.AnimationTimer;
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.canvas.Canvas;
import javafx.scene.canvas.GraphicsContext;
import javafx.scene.input.KeyCode;
import javafx.scene.layout.Pane;
import javafx.stage.Stage;

public class App extends Application {

  private double x = 0;

  public static void main(String[] args) {
    launch(args);
  }

  @Override
  public void start(Stage primaryStage) {
    Pane root = new Pane();
    Canvas canvas = new Canvas();
    canvas.heightProperty().bind(root.heightProperty());
    canvas.widthProperty().bind(root.widthProperty());

    Resources.load();
    GraphicsContext context2D = canvas.getGraphicsContext2D();
    Game game = new Game(context2D);

    new AnimationTimer() {
      @Override
      public void handle(long now) {
        Time.update(now);
        context2D.clearRect(0, 0, canvas.getWidth(), canvas.getHeight());
        context2D.drawImage(Resources.offlineResources1X, 40, 4, 44, 45, x, 0, 44, 45);
        game.update();
        x += Time.deltaTime * 120;
      }
    }.start();

    root.getChildren().add(canvas);
    Scene scene = new Scene(root, 600, 150);
    scene.setOnKeyPressed(event -> {
      if (event.getCode().equals(KeyCode.SPACE)) {
        Resources.Sounds.BUTTON_PRESS.play();
      }
      if (event.getCode().equals(KeyCode.P)) {
        game.pause();
      }
    });
    primaryStage.setScene(scene);
    primaryStage.setTitle("chrome://dino");
    primaryStage.setResizable(false);
    primaryStage.show();
  }
}
