/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fantasy0v0.dinoFx;

import java.io.IOException;
import java.io.InputStream;
import javafx.animation.AnimationTimer;
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.canvas.Canvas;
import javafx.scene.canvas.GraphicsContext;
import javafx.scene.image.Image;
import javafx.scene.layout.Pane;
import javafx.stage.Stage;

public class App extends Application {

  public static void main(String[] args) {
    launch(args);
  }

  @Override
  public void start(Stage primaryStage) throws IOException {
    Pane root = new Pane();
    Canvas canvas = new Canvas();
    canvas.heightProperty().bind(root.heightProperty());
    canvas.setHeight(600);
    canvas.widthProperty().bind(root.widthProperty());

    Module module = this.getClass().getModule();
    InputStream offlineResources1XResource = module.getResourceAsStream("offline-resources-1x.png");
    InputStream offlineResources2XResource = module.getResourceAsStream("offline-resources-2x.png");
    Image offlineResources1X = new Image(offlineResources1XResource);
    Image offlineResources2X = new Image(offlineResources2XResource);
    GraphicsContext context2D = canvas.getGraphicsContext2D();

    long FPS_60 = 1_000_000_000L / 60;

    long FPS_30 = 1_000_000_000L / 30;

    new AnimationTimer() {

      private long lastTimerCall = 0;

      @Override
      public void handle(long now) {
        if (now >= lastTimerCall) {
          context2D.clearRect(0, 0, canvas.getWidth(), canvas.getHeight());
          context2D.drawImage(offlineResources1X, 40, 4, 44, 45, 0, 0, 44, 45);
          lastTimerCall = now + (FPS_60 - (now - lastTimerCall));
        }
      }
    }.start();

    root.getChildren().add(canvas);
    Scene scene = new Scene(root, 600, 150);
    primaryStage.setScene(scene);
    primaryStage.setResizable(false);
    primaryStage.show();
  }
}
